languageCode = "ja"
title = "ぷらすのブログ"
hasCJKLanguage = true
pygmentsUseClasses = true
timeout = 60000
[params]
description = "Webエンジニアリングについて学んだことや考えたことをまとめるブログです"
OgpJsonBaseURL = "https://blog-api.p1ass.com/ogp?url="

[author]
name= "p1ass"

[taxonomies]
  tag = "tags"
  category = "categories"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
