baseURL = "https://blog.naoki.dev"
languageCode = "ja"
title = "ぷらすのブログ"
theme = "tale"
hasCJKLanguage = true
pygmentsUseClasses = true
timeout = 60000

[params]
description = "プログラミングや大学に関数することをつらつら書いていきます。"
OgpJsonBaseURL = "https://blog-api.naoki.dev/ogp?url="

[taxonomies]
  tag = "tags"
  category = "categories"
