baseURL = "https://blog.naoki.dev"
languageCode = "ja"
title = "ぷらすのブログ"
theme = "tale"
hasCJKLanguage = true
pygmentsUseClasses = true

[params]
description = "エンジニアリングに関することや自分のことをつらつら書いていきます。"

[taxonomies]
  tag = "tags"
  category = "categories"
