languageCode = "ja"
title = "ぷらすのブログ"
hasCJKLanguage = true
pygmentsUseClasses = true
timeout = 60000
googleAnalytics= "UA-127036212-7"
[params]
description = "Webエンジニアリングについて学んだことや考えたことをまとめるブログです"
OgpJsonBaseURL = "https://blog-api.p1ass.com/ogp?url="
css = ["custom.css"]

[author]
name= "p1ass"

[taxonomies]
  tag = "tags"
  category = "categories"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
