baseURL = "https://blog.p1ass.com"
languageCode = "ja"
title = "ぷらすのブログ"
theme = "tale"
hasCJKLanguage = true
pygmentsUseClasses = true
timeout = 60000
googleAnalytics= "UA-127036212-7"
[params]
description = "プログラミングや大学に関することをつらつら書いていきます。"
OgpJsonBaseURL = "https://blog-api.p1ass.com/ogp?url="
css = ["custom.css"]

[taxonomies]
  tag = "tags"
  category = "categories"
